from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from uuid import UUID

from app.config import settings


class OpenClawSyncResult(dict[str, Any]):
    pass


def sync_agent_to_openclaw(agent: dict[str, Any]) -> OpenClawSyncResult:
    openclaw_agent_id = _agent_id(agent)
    workspace_root = Path(settings.openclaw_workspace_root)
    workspace_dir = workspace_root / "app-agents" / str(agent["id"])
    workspace_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "AGENTS.md": _agents_md(agent, openclaw_agent_id),
        "SOUL.md": _soul_md(agent),
        "MEMORY.md": _memory_md(agent),
        "TOOLS.md": _tools_md(agent),
        "agent.json": _agent_json(agent, openclaw_agent_id),
    }

    written = []
    for filename, content in files.items():
        path = workspace_dir / filename
        path.write_text(content, encoding="utf-8")
        written.append(str(path))

    container_workspace = (
        f"{settings.openclaw_container_workspace_root}/app-agents/{agent['id']}"
    )
    _upsert_openclaw_config(agent, openclaw_agent_id, container_workspace)

    return OpenClawSyncResult(
        openclaw_agent_id=openclaw_agent_id,
        openclaw_workspace_path=container_workspace,
        local_workspace_path=str(workspace_dir),
        files=written,
    )


def _agent_id(agent: dict[str, Any]) -> str:
    suffix = str(agent["id"]).replace("-", "")[:12]
    name = re.sub(r"[^a-z0-9]+", "-", str(agent["name"]).lower()).strip("-")
    prefix = name[:28].strip("-") or "agent"
    return f"app-{prefix}-{suffix}"


def _agents_md(agent: dict[str, Any], openclaw_agent_id: str) -> str:
    return "\n".join(
        [
            f"# {agent['name']}",
            "",
            "<!-- Generated by the agent orchestration platform. Do not edit manually. -->",
            "",
            f"- OpenClaw agent id: `{openclaw_agent_id}`",
            f"- Role: {agent['role']}",
            f"- Model: {agent['model']}",
            f"- Channels: {', '.join(agent['channels']) or 'none'}",
            "",
            "## System Prompt",
            "",
            agent["system_prompt"],
            "",
            "## Interaction Rules",
            "",
            _bullet_list(agent["interaction_rules"]),
            "",
            "## Guardrails",
            "",
            _bullet_list(agent["guardrails"]),
            "",
            "## Schedules",
            "",
            _json_block(agent["schedules"]),
            "",
        ]
    )


def _soul_md(agent: dict[str, Any]) -> str:
    return "\n".join(
        [
            f"# SOUL.md - {agent['name']}",
            "",
            "<!-- Generated by the agent orchestration platform. Do not edit manually. -->",
            "",
            f"Role: {agent['role']}",
            "",
            "## Personality and Operating Prompt",
            "",
            agent["system_prompt"],
            "",
        ]
    )


def _memory_md(agent: dict[str, Any]) -> str:
    return "\n".join(
        [
            f"# MEMORY.md - {agent['name']}",
            "",
            "<!-- Generated by the agent orchestration platform. Do not edit manually. -->",
            "",
            _json_block(agent["memory"]),
            "",
        ]
    )


def _tools_md(agent: dict[str, Any]) -> str:
    return "\n".join(
        [
            f"# TOOLS.md - {agent['name']}",
            "",
            "<!-- Generated by the agent orchestration platform. Do not edit manually. -->",
            "",
            "## Tools",
            "",
            _bullet_list(agent["tools"]),
            "",
            "## Skills",
            "",
            _bullet_list(agent["skills"]),
            "",
        ]
    )


def _agent_json(agent: dict[str, Any], openclaw_agent_id: str) -> str:
    payload = {
        "source": "agent-platform",
        "generated_at": datetime.now(UTC).isoformat(),
        "openclaw_agent_id": openclaw_agent_id,
        "agent": _json_safe(agent),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _upsert_openclaw_config(
    agent: dict[str, Any],
    openclaw_agent_id: str,
    container_workspace: str,
) -> None:
    config_path = Path(settings.openclaw_config_path)
    config_path.parent.mkdir(parents=True, exist_ok=True)

    if config_path.exists():
        config = json.loads(config_path.read_text(encoding="utf-8"))
    else:
        config = {}

    agents = config.setdefault("agents", {}).setdefault("list", [])
    agents[:] = [
        existing for existing in agents if existing.get("id") != openclaw_agent_id
    ]
    agents.append(
        {
            "id": openclaw_agent_id,
            "name": agent["name"],
            "workspace": container_workspace,
            "agentDir": f"{settings.openclaw_container_agent_root}/{openclaw_agent_id}",
            "model": agent["model"],
        }
    )

    config_path.write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _bullet_list(items: list[Any]) -> str:
    if not items:
        return "- none"
    return "\n".join(f"- {item}" for item in items)


def _json_block(value: Any) -> str:
    return "```json\n" + json.dumps(value, indent=2, sort_keys=True) + "\n```"


def _json_safe(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _json_safe(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_json_safe(item) for item in value]
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime):
        return value.isoformat()
    return value
